import type { Metadata } from "next";
import "./globals.css";

import { Noto_Sans } from "next/font/google";

import { AuthProvider } from "@/lib/firebase/auth/auth-context";
import { getCurrentUser } from "@/lib/server/users/users_services";
import { Toaster } from "sonner";
import ReactQueryProvider from "@/lib/providers/react_queries/react_query_provider";

const notoSans = Noto_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getCurrentUser();
  return (
    <html lang="fr">
      <body className={`${notoSans.className}`}>
        <ReactQueryProvider>
          <AuthProvider user={user}>{children}</AuthProvider>
          <Toaster position="top-right" richColors />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
